export const filters = [
  {
    name: "Year",
    options: [
      "All",
      "Upcoming",
      "2020s",
      "2010s",
      "2000s",
      "1990s",
      "1980s",
      "1970s",
      "1960s",
      "1950s",
      "1940s",
      "1930s",
      "1920s",
      "1910s",
    ],
  },
  {
    name: "Rating",
    options: ["Lowest First", "Highest First"],
  },
  {
    name: "Genre",
    options: [
      "Action",
      "Adventure",
      "Animation",
      "Comedy",
      "Crime",
      "Documentary",
      "Drama",
      "Family",
      "Fantasy",
      "History",
      "Horror",
      "Music",
      "Mystery",
      "Romance",
      "Sci-Fi",
      "Thriller",
      "TV Movie",
      "War",
      "Western",
    ],
  },
];
